import { type Post } from '@/store/usePostStore';

export const postsBlogB: Post[] = [
  {
    id: 'b-001',
    title: '남편 차 냄새, 잔소리 대신 이렇게 바꿨어요',
    category: '일상',
    date: '3일 전',
    author: '살림하는엄마',
    authorProfileImage: '',
    headerImage: '',
    tags: ['남편 차', '차 냄새', '차량 방향제', '차량용품'],
    content: [
      { id: 'b001-1', type: 'text', content: '남편 차 탈 때마다 문 열자마자 답답한 냄새 올라오는데, 그걸 또 바로 말하기가 쉽지 않잖아요. 괜히 한마디 했다가 잔소리처럼 들릴까봐 저도 몇 번은 그냥 넘어갔거든요. 그래서 이번엔 말보다 먼저 손을 써보자 싶었는데요.' },
      { id: 'b001-2', type: 'image', src: '/posts/b-001-01.jpg', caption: '남편 차에 먼저 올려봤던 방향제' },
      { id: 'b001-3', type: 'text', content: '처음엔 집 앞 마트에서 송풍구에 끼우는 작은 방향제를 하나 사왔어요. 값도 부담 없고, 남편 차에 조용히 달아두기엔 이런 게 제일 무난해 보였거든요. 그래서 그날 바로 달아봤는데요.' },
      { id: 'b001-4', type: 'text', content: '달아둔 날 저녁에 남편이 \'오늘은 차가 좀 낫네?\' 하면서 먼저 말하더라고요. 저도 속으로는 잘됐다 싶었어요. 근데 그게 며칠이었어요.' },
      { id: 'b001-5', type: 'text', content: '사흘쯤 지나니까 향이 거의 안 느껴졌어요. 차 문 열 때마다 다시 꿉꿉한 냄새가 올라오는데, 또 갈아끼우자니 돈보다 손이 더 가잖아요. 남편 차 하나 때문에 제가 계속 챙겨야 한다고 생각하니까 그것도 좀 지치더라고요. 그래서 다른 쪽을 다시 보게 됐거든요.' },
      { id: 'b001-6', type: 'image', src: '/posts/b-001-02.jpg', caption: '며칠 쓰고 향이 약해진 남편 차 대시보드' },
      { id: 'b001-7', type: 'text', content: '그러다 우연히 본 건데, 햇빛 받으면 알아서 움직이는 타입이 있더라고요. 선도 안 보이고 대시보드에 올려두는 모양도 답답하지 않아서, 이건 제가 덜 손대도 되겠다 싶었거든요. 그래서 남편 차에 슬쩍 바꿔놨더니요.' },
      { id: 'b001-8', type: 'image', src: '/posts/b-001-03.jpg', caption: '지금 남편 차에 두고 있는 햇빛 타입' },
      { id: 'b001-9', type: 'text', content: '바꾼 뒤로는 차 탈 때마다 향이 은근하게 계속 남아 있어요. 대시보드도 전보다 덜 어수선해 보여서 남편이 먼저 닦아두는 걸 보면 마음에 든 거 맞는 거죠 ㅎㅎ' },
      { id: 'b001-10', type: 'text', content: '남편 차 냄새 때문에 저처럼 괜히 잔소리부터 하게 되셨다면, 자주 갈아끼우는 것보다 덜 손 가는 쪽을 같이 보시는 게 낫더라고요. 저는 이제 차 탈 때마다 먼저 말 꺼낼 일은 줄었어요.' },
    ],
    comments: [
      { id: 1, content: '저도 남편 차 타면 냄새 얘기할까 말까 늘 고민하게 돼요 ㅠㅠ', author: '꽃길걷자', timestamp: Date.now() - 3 * 86400000 + 4 * 3600000, likes: 4, isLiked: false },
      { id: 2, content: '맞아요~ 괜히 한마디 했다가 잔소리처럼 들릴까봐 조심하게 되더라고요 ㅎㅎ', author: '살림하는엄마', timestamp: Date.now() - 3 * 86400000 + 6 * 3600000, likes: 1, isLiked: false, parentId: 1 },
      { id: 3, content: '지금 쓰시는 건 어디서 보셨어요? 선 없는 타입 찾고 있었거든요', author: '다정한주부', timestamp: Date.now() - 3 * 86400000 + 26 * 3600000, likes: 2, isLiked: false },
      { id: 4, content: '저는 여기서 봤어요~ https://sjhur3601.cafe24.com/ 대시보드가 덜 복잡해 보여서 괜찮더라고요', author: '살림하는엄마', timestamp: Date.now() - 3 * 86400000 + 29 * 3600000, likes: 1, isLiked: false, parentId: 3 },
      { id: 5, content: '이런 건 남편이 먼저 알아봐주면 괜히 뿌듯하더라고요 ㅎㅎ', author: '햇살드는집', timestamp: Date.now() - 3 * 86400000 + 49 * 3600000, likes: 3, isLiked: false },
    ],
    isLiked: false,
    likeCount: 12,
    commentsEnabled: true,
    createdAt: Date.now() - 3 * 86400000,
  },
  {
    id: 'b-002',
    title: '남편 생일 선물, 서랍행 아닌 걸로 골랐어요',
    category: '일상',
    date: '5일 전',
    author: '살림하는엄마',
    authorProfileImage: '',
    headerImage: '',
    tags: ['남편 생일 선물', '실용적인 선물', '남편 선물', '차량용품'],
    content: [
      { id: 'b002-1', type: 'text', content: '남편 생일 선물 고를 때 제일 머리 아픈 게, 괜히 비싸게 샀는데 몇 번 안 쓰면 주는 사람만 더 허무하잖아요. 셔츠도 지갑도 이미 있고, 이번엔 진짜 매일 쓰는 걸 골라야겠다 싶었거든요. 그래서 며칠 전부터 후보를 늘어놔봤는데요.' },
      { id: 'b002-2', type: 'image', src: '/posts/b-002-01.jpg', caption: '남편 생일 선물 후보를 모아본 날' },
      { id: 'b002-3', type: 'text', content: '거실 테이블에 텀블러, 양말 세트, 작은 가방까지 올려놓고 한참 봤어요. 남편이 평소 어디서 제일 오래 시간을 보내나 생각해보니까, 집보다 차 안에서 보내는 시간이 더 길더라고요. 그래서 그쪽부터 다시 보게 됐는데요.' },
      { id: 'b002-4', type: 'text', content: '그래서 이번 남편 생일 선물은 보기 좋은 것보다 차 안에서 바로 써보게 되는 쪽으로 마음이 기울었어요. 대시보드가 복잡하지 않으면서 분위기만 은근하게 바뀌면 좋겠다 싶었거든요. 근데 제가 이렇게 고른 데는 이유가 있었어요.' },
      { id: 'b002-5', type: 'text', content: '예전에 멋으로 고른 선물이 있었는데, 몇 번만 쓰고 서랍 안으로 들어가버렸어요. 괜히 \'잘 쓰고 있어?\' 묻기도 민망하고, 받는 사람도 미안한 표정 짓는 게 더 속상하잖아요. 남편 생일 선물도 또 그런 식이면 주는 저만 들뜨고 끝나는 거라, 이번엔 그게 제일 무서웠거든요. 그러다 마지막에 딱 남는 게 있더라고요.' },
      { id: 'b002-6', type: 'image', src: '/posts/b-002-02.jpg', caption: '포장해두고도 끝까지 고민했던 생일 선물' },
      { id: 'b002-7', type: 'text', content: '우연히 본 게 햇빛 받으면 알아서 돌아가는 타입이었어요. 선 연결이 없으니까 선물 포장해도 생활용품처럼 투박하지 않고, 차에 두면 바로 달라질 것 같더라고요. 그래서 생일 아침에 건네봤더니요.' },
      { id: 'b002-8', type: 'image', src: '/posts/b-002-03.jpg', caption: '남편 생일에 준비한 실용적인 선물' },
      { id: 'b002-9', type: 'text', content: '남편이 받자마자 차에 먼저 올려봐야겠다면서 웃더라고요. 며칠 지나도 그대로 쓰고 있는 걸 보니까, 이번엔 진짜 서랍행은 아니구나 싶어서 저도 마음이 놓였어요 ㅎㅎ' },
      { id: 'b002-10', type: 'text', content: '남편 생일 선물은 결국 가격보다 얼마나 자주 손이 가느냐가 더 중요하더라고요. 저처럼 예쁜 것 샀다가 안 쓰는 모습이 더 아쉬우셨다면, 매일 보는 자리에서 바로 쓰는 쪽을 먼저 보셔도 괜찮을 거예요.' },
    ],
    comments: [
      { id: 1, content: '저도 남편 생일 선물만 되면 진짜 뭘 사야 하나 막막해져요 ㅠㅠ', author: '봄날햇살', timestamp: Date.now() - 5 * 86400000 + 4 * 3600000, likes: 3, isLiked: false },
      { id: 2, content: '맞아요~ 괜히 멋으로 골랐다가 안 쓰면 더 속상하더라고요 ㅎㅎ', author: '살림하는엄마', timestamp: Date.now() - 5 * 86400000 + 6 * 3600000, likes: 1, isLiked: false, parentId: 1 },
      { id: 3, content: '포장했을 때도 선물 느낌은 괜찮았나요? 너무 생활용품 같을까봐요', author: '고운살림', timestamp: Date.now() - 5 * 86400000 + 26 * 3600000, likes: 2, isLiked: false },
      { id: 4, content: '저는 여기서 보고 골랐어요~ https://sjhur3601.cafe24.com/ 포장해두니 생각보다 단정해서 선물용으로도 괜찮더라고요', author: '살림하는엄마', timestamp: Date.now() - 5 * 86400000 + 29 * 3600000, likes: 1, isLiked: false, parentId: 3 },
      { id: 5, content: '남편들은 결국 매일 쓰는 게 제일 기억에 남는 것 같아요 ㅋㅋ', author: '소박한오늘', timestamp: Date.now() - 5 * 86400000 + 49 * 3600000, likes: 2, isLiked: false },
    ],
    isLiked: false,
    likeCount: 14,
    commentsEnabled: true,
    createdAt: Date.now() - 5 * 86400000,
  },
  {
    id: 'b-003',
    title: '실용적인 선물, 안 쓰면 주는 사람만 민망하잖아요',
    category: '일상',
    date: '7일 전',
    author: '살림하는엄마',
    authorProfileImage: '',
    headerImage: '',
    tags: ['실용적인 선물', '선물 추천', '남편 선물', '차량용품'],
    content: [
      { id: 'b003-1', type: 'text', content: '실용적인 선물 찾는다고 하면서도 막상 고를 땐 또 포장 예쁜 쪽으로 눈이 가잖아요. 근데 정성껏 챙겨준 게 몇 번 쓰고 그대로 남아 있으면, 주는 사람 마음이 더 허전하더라고요. 저도 그걸 몇 번 겪고 나니까 기준이 좀 달라졌는데요.' },
      { id: 'b003-2', type: 'image', src: '/posts/b-003-01.jpg', caption: '서랍에 남아 있던 안 쓰는 선물들' },
      { id: 'b003-3', type: 'text', content: '예전엔 향수나 소품처럼 보기 좋은 걸 먼저 골랐어요. 처음 건넬 땐 반응도 괜찮은데, 생활이 바빠지면 결국 자주 손이 가는 건 따로 있더라고요. 그래서 그때부터 보는 눈이 좀 달라졌는데요.' },
      { id: 'b003-4', type: 'text', content: '그래서 요즘은 실용적인 선물을 볼 때 \'받고 바로 쓰게 되나\'를 먼저 생각해요. 꺼내는 과정이 번거롭지 않고, 일상에 그냥 스며드는 게 훨씬 오래 남거든요. 근데 이 기준이 생긴 데는 이유가 있었어요.' },
      { id: 'b003-5', type: 'text', content: '한 번은 정말 공들여 고른 선물이 있었는데, 다음에 갔더니 그대로 서랍 한쪽에 있더라고요. 괜히 \'마음에 안 들었나?\' 싶어서 저 혼자 민망하고, 받는 사람도 미안한 눈치라 서로 불편했어요. 실용적인 선물은 비싸고 근사한 것보다 계속 손이 가야 의미가 있구나 싶으니까, 그 뒤로는 보는 포인트가 완전히 바뀌었거든요. 그래서 요즘은 아예 다른 쪽부터 찾게 됐는데요.' },
      { id: 'b003-6', type: 'image', src: '/posts/b-003-02.jpg', caption: '몇 번 쓰고 그대로 둔 선물' },
      { id: 'b003-7', type: 'text', content: '특히 차에서 보내는 시간이 있는 사람은 차 안에서 바로 쓰는 게 만족도가 높더라고요. 우연히 본 햇빛 받으면 움직이는 타입은 선도 안 보이고 설치가 어렵지 않아, 받는 사람이 바로 써볼 수 있겠다 싶었거든요. 그래서 그날은 이런 쪽을 더 들여다보게 됐는데요.' },
      { id: 'b003-8', type: 'image', src: '/posts/b-003-03.jpg', caption: '매일 쓰게 되는 차 안 실용템' },
      { id: 'b003-9', type: 'text', content: '막상 건네고 나서 바로 차에 올려두는 걸 보면 주는 사람도 마음이 놓여요. 몇 주 지나도 계속 쓰는 게 보이면, 그제야 실용적인 선물 제대로 골랐구나 싶더라고요 ㅎㅎ' },
      { id: 'b003-10', type: 'text', content: '실용적인 선물은 화려한 것보다 생활 안에 자연스럽게 남는 게 더 중요하더라고요. 저처럼 안 쓰는 선물 보고 괜히 민망했던 적 있으시면, 받자마자 바로 쓸 장면이 떠오르는지부터 보셔도 괜찮아요.' },
    ],
    comments: [
      { id: 1, content: '차량용품 선물은 생각 못 했는데 진짜 좋은 아이디어네요.', author: '행복한정리', timestamp: Date.now() - 7 * 86400000 + 4 * 3600000, likes: 3, isLiked: false },
      { id: 2, content: '맞아요~ 매일 쓰는 쪽이 결국 만족도가 제일 높더라고요 ㅎㅎ', author: '살림하는엄마', timestamp: Date.now() - 7 * 86400000 + 6 * 3600000, likes: 1, isLiked: false, parentId: 1 },
      { id: 3, content: '받자마자 바로 써볼 수 있는 게 확실히 더 괜찮은 것 같죠?', author: '우리집일상', timestamp: Date.now() - 7 * 86400000 + 26 * 3600000, likes: 2, isLiked: false },
      { id: 4, content: '저는 여기 참고했어요~ https://sjhur3601.cafe24.com/ 바로 올려둘 수 있는 쪽이라 부담이 덜하더라고요', author: '살림하는엄마', timestamp: Date.now() - 7 * 86400000 + 29 * 3600000, likes: 1, isLiked: false, parentId: 3 },
      { id: 5, content: '안 쓰는 선물보다 이런 게 훨씬 오래 기억에 남는 것 같아요 ㅎㅎ', author: '따뜻한살림', timestamp: Date.now() - 7 * 86400000 + 49 * 3600000, likes: 2, isLiked: false },
    ],
    isLiked: false,
    likeCount: 10,
    commentsEnabled: true,
    createdAt: Date.now() - 7 * 86400000,
  },
  {
    id: 'b-004',
    title: '다이소 방향제 1주일 써보고 결국 바꿨어요',
    category: '차량용품',
    date: '9일 전',
    author: '살림하는엄마',
    authorProfileImage: '',
    headerImage: '',
    tags: ['다이소 방향제 추천', '방향제 추천', '차량 방향제', '남편 차'],
    content: [
      // Act 1: Hook
      { id: 'b004-1', type: 'text', content: '남편 차 타면서 \'냄새 나는데\' 싶으면서도 차마 말을 못 한 적 있잖아요. 잔소리처럼 들릴까봐요. 그래서 말 없이 다이소 방향제를 하나 사왔는데요.' },
      { id: 'b004-2', type: 'image', src: '/posts/b-004-01.jpg', caption: '다이소에서 사 온 차량용 방향제' },
      // Act 2: 시도
      { id: 'b004-3', type: 'text', content: '천 원짜리 고체 타입이었어요. 다이소 향 코너 지나가다 하나 집어온 건데, 남편 차 송풍구에 끼우는 거였거든요.' },
      { id: 'b004-4', type: 'text', content: '달아주니까 남편이 "오 향 괜찮은데?" 하면서 좋아했어요. 차 탈 때마다 은은하게 나니까 저도 기분이 좋았거든요. 근데 그게 며칠이었어요.' },
      // Act 3: 실패
      { id: 'b004-5', type: 'text', content: '일주일 지나니까 향이 거의 사라졌어요. 코를 대야 겨우 나는 수준이라, 남편도 "이거 끝난 것 같은데?" 하더라고요. 천 원이라 또 사면 되긴 한데, 매번 갈아끼우는 것도 결국 귀찮잖아요. 그래서 다른 거 없나 찾아봤거든요.' },
      { id: 'b004-6', type: 'image', src: '/posts/b-004-02.jpg', caption: '남편 차 대시보드에 올려둔 모습' },
      // Act 4: 발견
      { id: 'b004-7', type: 'text', content: '그러다 우연히 본 건데, 햇빛 받으면 알아서 돌아가는 타입이 있더라고요. 선도 없고 충전도 필요 없다길래, 이게 진짜 되나 싶었거든요. 그래서 남편한테 보여줬더니요.' },
      { id: 'b004-8', type: 'image', src: '/posts/b-004-03.jpg', caption: '지금 남편 차에 올려둔 방향제' },
      // Act 5: 만족 + 정리
      { id: 'b004-9', type: 'text', content: '바꾼 지 2주 정도 됐는데, 향이 은은하게 계속 유지되고 있어요. 주차번호판 겸용이라 대시보드도 깔끔해졌고요. 남편이 직접 닦고 관리하는 거 보면 마음에 든 거 맞는 거죠 ㅎㅎ' },
      { id: 'b004-10', type: 'text', content: '다이소 방향제가 나쁜 건 아니에요. 가볍게 테스트해보기엔 좋거든요. 근데 저처럼 매번 갈아끼우기 귀찮으면, 다른 쪽도 같이 보시는 게 나을 거예요.' },
    ],
    comments: [
      { id: 1, content: '다이소 방향제 저도 써봤는데 진짜 일주일이면 끝이에요 ㅠㅠ', author: '꽃피는날', timestamp: Date.now() - 9 * 86400000 + 4 * 3600000, likes: 4, isLiked: false },
      { id: 2, content: '맞아요~ 처음엔 괜찮은데 금방 날아가더라고요 ㅎㅎ', author: '살림하는엄마', timestamp: Date.now() - 9 * 86400000 + 6 * 3600000, likes: 1, isLiked: false, parentId: 1 },
      { id: 3, content: '혹시 지금 쓰시는 거 어디서 구매하셨어요? 선 없는 거 찾고 있었거든요', author: '차안이좋아', timestamp: Date.now() - 8 * 86400000 + 2 * 3600000, likes: 2, isLiked: false },
      { id: 4, content: '여기서 봤어요~ https://sjhur3601.cafe24.com/ 번호판 겸용이라 깔끔해요', author: '살림하는엄마', timestamp: Date.now() - 8 * 86400000 + 5 * 3600000, likes: 1, isLiked: false, parentId: 3 },
      { id: 5, content: '남편한테 보여줬더니 본인이 직접 사겠대요 ㅋㅋ', author: '두아이맘', timestamp: Date.now() - 7 * 86400000 + 1 * 3600000, likes: 3, isLiked: false },
    ],
    isLiked: false,
    likeCount: 16,
    commentsEnabled: true,
    createdAt: Date.now() - 9 * 86400000,
  },
  {
    id: 'b-005',
    title: '자동차 꾸미기, 남편 차는 덜어내니까 낫더라고요',
    category: '일상',
    date: '12일 전',
    author: '살림하는엄마',
    authorProfileImage: '',
    headerImage: '',
    tags: ['자동차 꾸미기', '남편 차', '차량 인테리어', '깜짝 선물'],
    content: [
      { id: 'b005-1', type: 'text', content: '자동차 꾸미기라고 하면 뭘 더 올려야 하나부터 생각하게 되잖아요. 근데 남편 차는 원래 복잡한 걸 싫어해서, 티 안 나게 정리되는 쪽이 더 낫더라고요. 그래서 이번에도 대시보드만 살짝 손봐보자 싶었는데요.' },
      { id: 'b005-2', type: 'image', src: '/posts/b-005-01.jpg', caption: '정리하기 전 남편 차 대시보드' },
      { id: 'b005-3', type: 'text', content: '처음엔 작은 장식 하나 놓고, 번호 적는 것도 따로 두고, 향 나는 것도 하나 올려봤어요. 집에서 볼 땐 알차고 귀엽다 싶었는데, 막상 남편 차에 두니까 생각보다 이것저것 많아 보이더라고요. 그래도 일단 하루는 두고 봤는데요.' },
      { id: 'b005-4', type: 'text', content: '그래도 하루 정도는 괜찮은가 싶었어요. 근데 차 문 열 때마다 시선이 분산되고, 급하게 브레이크 밟을 때마다 작은 것들이 미세하게 움직이니까 제가 봐도 마음이 불편하더라고요. 이대로 두면 남편이 먼저 말하겠다 싶었거든요.' },
      { id: 'b005-5', type: 'text', content: '남편이 예전에도 \'차가 좀 정신없네\' 한 적이 있거든요. 그 말 다시 들으면 자동차 꾸미기 한답시고 제 취향만 앞세운 셈이라 더 민망하잖아요. 타는 사람이 편해야 하는데 보기만 귀여운 걸 잔뜩 올려두면 결국 불편만 남더라고요. 그래서 하나로 정리되는 쪽을 다시 찾게 됐거든요.' },
      { id: 'b005-6', type: 'image', src: '/posts/b-005-02.jpg', caption: '이것저것 올려뒀다가 복잡해진 대시보드' },
      { id: 'b005-7', type: 'text', content: '그러다 우연히 본 게 햇빛 받으면 알아서 움직이는 타입이었어요. 선도 안 보이고 번호 적는 부분까지 같이 있어서, 따로 올려둔 걸 줄일 수 있겠다 싶었거든요. 그래서 조용히 바꿔놨더니요.' },
      { id: 'b005-8', type: 'image', src: '/posts/b-005-03.jpg', caption: '하나로 정리해둔 지금 남편 차' },
      { id: 'b005-9', type: 'text', content: '퇴근하고 탄 남편이 \'어? 차가 왜 이렇게 편안해 보이지?\' 하더라고요. 제가 바꿨다고 하니까 이런 건 괜찮다길래, 자동차 꾸미기도 결국 덜어내는 쪽이 맞는 거구나 싶었어요 ㅎㅎ' },
      { id: 'b005-10', type: 'text', content: '자동차 꾸미기는 많이 올려두는 것보다 타는 사람이 답답하지 않은 게 먼저더라고요. 저처럼 남편 차를 소소하게 손보고 싶으시면, 이것저것 더하기보다 하나로 정리되는 쪽부터 보셔도 괜찮을 거예요.' },
    ],
    comments: [
      { id: 1, content: '저도 남편 차 한번 몰래 손봐줘야겠어요 ㅎㅎ', author: '정리하는하루', timestamp: Date.now() - 12 * 86400000 + 4 * 3600000, likes: 3, isLiked: false },
      { id: 2, content: '한번 해보세요~ 너무 티 나지 않게 바꿔두면 반응 보는 재미가 있더라고요 ㅎㅎ', author: '살림하는엄마', timestamp: Date.now() - 12 * 86400000 + 6 * 3600000, likes: 1, isLiked: false, parentId: 1 },
      { id: 3, content: '번호판이랑 같이 되는 거면 더 깔끔하겠네요. 어디서 보셨어요?', author: '아침살림', timestamp: Date.now() - 12 * 86400000 + 26 * 3600000, likes: 2, isLiked: false },
      { id: 4, content: '저는 여기서 봤어요~ https://sjhur3601.cafe24.com/ 하나로 정리되니까 대시보드가 훨씬 편안해 보이더라고요', author: '살림하는엄마', timestamp: Date.now() - 12 * 86400000 + 29 * 3600000, likes: 1, isLiked: false, parentId: 3 },
      { id: 5, content: '남편들은 티 안 나게 바뀐 걸 더 좋아하더라고요 ㅋㅋ', author: '오전의살림', timestamp: Date.now() - 12 * 86400000 + 49 * 3600000, likes: 2, isLiked: false },
    ],
    isLiked: false,
    likeCount: 12,
    commentsEnabled: true,
    createdAt: Date.now() - 12 * 86400000,
  },
  {
    id: 'b-006',
    title: '커피향 방향제, 이것저것 써보다가 결국 정착했어요',
    category: '차량용품',
    date: '14일 전',
    author: '살림하는엄마',
    authorProfileImage: '',
    headerImage: '',
    tags: ['커피향 방향제', '커피향', '차량 방향제', '방향제 추천'],
    content: [
      { id: 'b006-1', type: 'text', content: '커피향 방향제 찾는 분들 마음 저도 잘 알거든요. 저도 아침에 차 문 열었을 때 커피 냄새가 살짝 올라오면 기분 좋겠다 싶어서 이것저것 써봤어요. 근데 막상 차 안에서는 생각보다 맞는 걸 찾기가 쉽지 않더라고요. 그래서 한동안 비교해봤는데요.' },
      { id: 'b006-2', type: 'image', src: '/posts/b-006-01.jpg', caption: '커피향 계열로 이것저것 비교해본 날' },
      { id: 'b006-3', type: 'text', content: '처음엔 달달한 쪽도 써보고, 묵직한 원두 느낌 난다는 것도 가져와봤어요. 부엌 테이블에서 맡아보면 다 그럴듯한데, 차 안에 두면 느낌이 완전히 달라지더라고요. 그래서 기준을 다시 세우게 됐는데요.' },
      { id: 'b006-4', type: 'text', content: '제가 원한 건 아침에 문 열었을 때만 은은하게 스치는 정도였어요. 그래서 향이 너무 세지 않고 대시보드도 답답해 보이지 않는 쪽으로 기준을 세웠거든요. 근데 그 기준 맞추는 게 제일 어렵더라고요. 거기서부터가 문제였거든요.' },
      { id: 'b006-5', type: 'text', content: '어떤 건 커피향 방향제라더니 시럽 같은 단내가 더 세서 오래 타고 있으면 머리가 답답했어요. 또 어떤 건 처음 하루만 커피 같고 며칠 지나면 그냥 밋밋해져서, 이걸 왜 차에 두나 싶더라고요. 좋아하는 향인데도 차 안이 무거워지면 손이 안 가니까 더 까다로워졌죠. 그래서 보는 포인트를 아예 바꿔보게 됐거든요.' },
      { id: 'b006-6', type: 'image', src: '/posts/b-006-02.jpg', caption: '향은 괜찮아도 답답했던 이전 타입들' },
      { id: 'b006-7', type: 'text', content: '그러다 우연히 본 게 햇빛 받으면 알아서 움직이는 타입이었어요. 향을 확 밀어붙이는 느낌이 아니라 문 열었을 때만 살짝 느껴질 것 같아서, 이건 차 안에서도 괜찮겠다 싶었거든요. 그래서 결국 이걸로 바꿔봤는데요.' },
      { id: 'b006-8', type: 'image', src: '/posts/b-006-03.jpg', caption: '지금 차 안에서 쓰는 커피향 타입' },
      { id: 'b006-9', type: 'text', content: '지금은 아침에 차 문 열면 커피향이 과하게 치고 오지 않고 은은하게 남아요. 오래 타고 있어도 머리 아픈 느낌이 없고 대시보드도 깔끔해서, 저는 이 정도가 딱 좋더라고요 ㅎㅎ' },
      { id: 'b006-10', type: 'text', content: '커피향 방향제 찾으시면 진한 첫향보다 차 안에서 오래 있어도 답답하지 않은지를 먼저 보셔야 하더라고요. 저처럼 커피 느낌은 좋지만 무거운 건 싫으셨다면 이런 쪽이 더 잘 맞을 거예요.' },
    ],
    comments: [
      { id: 1, content: '커피향 좋아하는데 차 안에서는 너무 진하면 머리 아프더라고요 ㅠ', author: '주부메모', timestamp: Date.now() - 14 * 86400000 + 4 * 3600000, likes: 3, isLiked: false },
      { id: 2, content: '맞아요~ 저도 달달한 쪽은 오래 타면 좀 답답해서 못 쓰겠더라고요', author: '살림하는엄마', timestamp: Date.now() - 14 * 86400000 + 6 * 3600000, likes: 1, isLiked: false, parentId: 1 },
      { id: 3, content: '커피향 말고 다른 향도 같이 있나요? 은은한 쪽이면 보고 싶어요', author: '가을하루', timestamp: Date.now() - 14 * 86400000 + 26 * 3600000, likes: 2, isLiked: false },
      { id: 4, content: '저는 여기서 봤어요~ https://sjhur3601.cafe24.com/ 다른 향도 있던데 저는 과하지 않은 커피 쪽이 제일 낫더라고요', author: '살림하는엄마', timestamp: Date.now() - 14 * 86400000 + 29 * 3600000, likes: 1, isLiked: false, parentId: 3 },
      { id: 5, content: '은은한 커피향이면 아침 출근길에 딱일 것 같네요 ㅎㅎ', author: '소소한메모', timestamp: Date.now() - 14 * 86400000 + 49 * 3600000, likes: 2, isLiked: false },
    ],
    isLiked: false,
    likeCount: 17,
    commentsEnabled: true,
    createdAt: Date.now() - 14 * 86400000,
  },
];
