import { type Post } from '@/store/usePostStore';

export const postsBlogB: Post[] = [
  {
    id: 'b-001',
    title: '남편 차 탈 때마다 잔소리했는데 이제 안 해요',
    category: '일상',
    date: '3일 전',
    author: '살림하는엄마',
    authorProfileImage: '',
    headerImage: '',
    tags: ['남편차', '방향제', '차량용품', '일상'],
    content: [
      { id: 'b001-1', type: 'text', content: '남편 차에 타면 항상 냄새가 좀 그랬거든요. 잔소리하기도 그렇고...' },
      { id: 'b001-3', type: 'text', content: '그래서 몰래 하나 올려놨는데 "이거 뭐야?" 하면서 좋아하더라고요 ㅎㅎ' },
      { id: 'b001-5', type: 'text', content: '태양열로 돌아가는 거라 선 연결도 없고, 주차번호판이랑 겸용이라 대시보드도 깔끔해요.' },
      { id: 'b001-6', type: 'text', content: '향이 은은해서 저도 옆에 타면 기분이 좋아지더라고요. 남편도 만족 중 ㅎ' },
    ],
    comments: [
      { id: 1, content: '오 이거 어디서 사셨어요? 저도 남편 차에 하나 해주고 싶어요~', author: '꽃길걷자', timestamp: Date.now() - 172800000, likes: 3, isLiked: false },
      { id: 2, content: '여기서 샀어요~ https://sjhur3601.cafe24.com/ 포장도 괜찮아서 선물용으로도 좋더라고요', author: '살림하는엄마', timestamp: Date.now() - 169200000, likes: 1, isLiked: false, parentId: 1 },
    ],
    isLiked: false,
    likeCount: 12,
    commentsEnabled: true,
    createdAt: Date.now() - 259200000,
  },
  {
    id: 'b-002',
    title: '남편 생일 선물 뭐 사지? 실용적인 거 골라봤어요',
    category: '일상',
    date: '5일 전',
    author: '살림하는엄마',
    authorProfileImage: '',
    headerImage: '',
    tags: ['남편 생일 선물', '실용적 선물', '남편 선물', '차량용품'],
    content: [
      { id: 'b002-1', type: 'text', content: '남편 생일만 다가오면 늘 고민이더라고요. 지갑이나 셔츠는 이미 많고, 안 쓰는 선물은 결국 서랍으로 들어가니까요.' },
      { id: 'b002-3', type: 'text', content: '이번엔 정말 자주 쓸 만한 걸로만 후보를 추렸어요. 텀블러, 운동화, 차량에서 쓰는 소소한 물건까지 놓고 봤는데 결국 매일 눈에 들어오는 게 제일 낫겠다 싶었거든요.' },
      { id: 'b002-4', type: 'text', content: '남편이 차에 있는 시간이 은근 길어서, 대시보드 쪽을 깔끔하게 해주는 쪽으로 골랐습니다. 포장해 주니까 생일 선물 느낌도 나고, 막상 써보니 반응도 괜찮더라고요.' },
      { id: 'b002-6', type: 'text', content: '비싼 것보다 자주 쓰는 게 기억에 남는다는 걸 또 느꼈어요. 남편 생일 선물 고민되시면 멋보다 실용 쪽을 먼저 보셔도 괜찮아요.' },
    ],
    comments: [
      { id: 1, content: '저도 남편 선물 고민인데 이거 괜찮네요~', author: '봄날햇살', timestamp: Date.now() - 5 * 86400000 + 3 * 3600000, likes: 2, isLiked: false },
      { id: 2, content: '감사해요~ 저는 여기서 보고 골랐어요. https://sjhur3601.cafe24.com/ 실용적인 쪽 좋아하시면 무난하더라고요.', author: '살림하는엄마', timestamp: Date.now() - 5 * 86400000 + 5 * 3600000, likes: 1, isLiked: false, parentId: 1 },
      { id: 3, content: '포장도 괜찮았나요?', author: '고운살림', timestamp: Date.now() - 5 * 86400000 + 12 * 3600000, likes: 1, isLiked: false },
      { id: 4, content: '네, 선물하기 크게 민망하지 않았어요. 링크도 같이 남겨둘게요~ https://sjhur3601.cafe24.com/', author: '살림하는엄마', timestamp: Date.now() - 5 * 86400000 + 14 * 3600000, likes: 0, isLiked: false, parentId: 3 },
    ],
    isLiked: false,
    likeCount: 14,
    commentsEnabled: true,
    createdAt: Date.now() - 5 * 86400000,
  },
  {
    id: 'b-003',
    title: '실용적인 선물 고르는 법, 안 쓰면 의미 없잖아요',
    category: '일상',
    date: '7일 전',
    author: '살림하는엄마',
    authorProfileImage: '',
    headerImage: '',
    tags: ['실용적인 선물', '선물 추천', '가성비 선물', '차량용품'],
    content: [
      { id: 'b003-1', type: 'text', content: '다들 이런 경험 있지 않으세요? 정성껏 선물했는데 몇 번 쓰다가 그대로 넣어두는 거요. 그럴 때마다 괜히 제가 더 아깝더라고요.' },
      { id: 'b003-3', type: 'text', content: '그래서 요즘은 예쁜 것보다 자주 쓰는 걸 먼저 봅니다. 집에서든 차에서든 하루에 한 번 이상 눈에 들어오는 물건이면 실패 확률이 확실히 줄어요.' },
      { id: 'b003-4', type: 'text', content: '특히 차에서 보내는 시간이 있는 사람은 차량에서 쓰는 물건도 의외로 만족도가 높더라고요. 실용적인 선물은 받는 사람이 바로 써볼 수 있어야 한다는 걸 요즘 더 느껴요.' },
      { id: 'b003-6', type: 'text', content: '결국 선물은 마음도 중요하지만, 생활 속에 자연스럽게 남는 게 더 오래 기억되는 것 같아요. 저처럼 실용적인 선물 찾는 분들께는 이 기준이 제일 편했습니다.' },
    ],
    comments: [
      { id: 1, content: '차량용품 선물 생각 못 했는데 좋은 아이디어네요.', author: '행복한정리', timestamp: Date.now() - 7 * 86400000 + 4 * 3600000, likes: 2, isLiked: false },
      { id: 2, content: '맞아요~ 매일 쓰는 쪽이 만족도가 높더라고요. 참고하실 링크 남겨둘게요. https://sjhur3601.cafe24.com/', author: '살림하는엄마', timestamp: Date.now() - 7 * 86400000 + 6 * 3600000, likes: 1, isLiked: false, parentId: 1 },
      { id: 3, content: '안 쓰는 선물 받으면 주는 사람도 속상하죠 ㅠ', author: '우리집일상', timestamp: Date.now() - 6 * 86400000 + 2 * 3600000, likes: 1, isLiked: false },
      { id: 4, content: '그러니까요. 그래서 저는 요즘 실용부터 따지게 되네요 ㅎㅎ https://sjhur3601.cafe24.com/', author: '살림하는엄마', timestamp: Date.now() - 6 * 86400000 + 4 * 3600000, likes: 0, isLiked: false, parentId: 3 },
    ],
    isLiked: false,
    likeCount: 10,
    commentsEnabled: true,
    createdAt: Date.now() - 7 * 86400000,
  },
  {
    id: 'b-004',
    title: '다이소 방향제 써봤는데.. 남편 차엔 이게 나았어요',
    category: '차량용품',
    date: '9일 전',
    author: '살림하는엄마',
    authorProfileImage: '',
    headerImage: '',
    tags: ['다이소 방향제 추천', '방향제 추천', '차량 방향제', '남편 차'],
    content: [
      { id: 'b004-1', type: 'text', content: '남편 차 냄새가 좀 신경 쓰여서 다이소 방향제를 먼저 사봤거든요. 가격이 가볍고 구하기 쉬워서 테스트용으로는 좋았어요.' },
      { id: 'b004-3', type: 'text', content: '그런데 향이 생각보다 빨리 빠지더라고요. 처음엔 괜찮다가 며칠 지나면 거의 안 느껴져서 좀 아쉬웠어요.' },
      { id: 'b004-4', type: 'text', content: '그래서 요즘은 햇빛 들면 움직이는 타입으로 바꿔뒀는데, 선이 안 보여서 더 깔끔하고 향도 은은하게 오래가서 남편 차에는 이쪽이 더 맞았습니다.' },
      { id: 'b004-6', type: 'text', content: '다이소 쪽은 짧게 써보기 좋고, 오래 둘 거면 지금 쓰는 쪽이 편했어요. 남편 차처럼 물건 많은 차엔 덜 복잡한 게 제일이더라고요.' },
    ],
    comments: [
      { id: 1, content: '남편 차에 어떤 거 올려놓으셨어요?', author: '살림메모', timestamp: Date.now() - 9 * 86400000 + 3 * 3600000, likes: 3, isLiked: false },
      { id: 2, content: '햇빛 받으면 돌아가고 번호 보는 기능도 같이 있는 타입이에요~ 저는 여기서 봤어요. https://sjhur3601.cafe24.com/', author: '살림하는엄마', timestamp: Date.now() - 9 * 86400000 + 5 * 3600000, likes: 1, isLiked: false, parentId: 1 },
      { id: 3, content: '향 오래가면 저도 바꿔보고 싶네요.', author: '엄마의시간', timestamp: Date.now() - 8 * 86400000 + 1 * 3600000, likes: 1, isLiked: false },
      { id: 4, content: '저희 집은 만족했어요 ㅎㅎ 링크 같이 남겨둘게요. https://sjhur3601.cafe24.com/', author: '살림하는엄마', timestamp: Date.now() - 8 * 86400000 + 4 * 3600000, likes: 0, isLiked: false, parentId: 3 },
    ],
    isLiked: false,
    likeCount: 16,
    commentsEnabled: true,
    createdAt: Date.now() - 9 * 86400000,
  },
  {
    id: 'b-005',
    title: '남편 차 몰래 꾸며줬더니 반응이 ㅎㅎ',
    category: '일상',
    date: '12일 전',
    author: '살림하는엄마',
    authorProfileImage: '',
    headerImage: '',
    tags: ['자동차 꾸미기', '남편 차', '차량 인테리어', '깜짝 선물'],
    content: [
      { id: 'b005-1', type: 'text', content: '남편 차가 워낙 무심한 스타일이라 제가 가끔 소소하게 손보거든요. 이번엔 티 안 나게 대시보드 쪽만 조금 정리해봤어요.' },
      { id: 'b005-3', type: 'text', content: '원래는 작은 물건이 이것저것 흩어져 있어서 보기엔 별거 아닌데 은근 지저분해 보였어요. 그래서 번호 보는 부분이랑 향 관련 물건을 같이 정리되는 쪽으로 바꿔놨죠.' },
      { id: 'b005-4', type: 'text', content: '남편이 퇴근하고 타더니 "어? 차가 왜 이렇게 깔끔해졌지" 하더라고요. 제가 해놨다고 하니 웃으면서 이런 건 괜찮다고 해서 저도 괜히 뿌듯했어요 ㅎㅎ' },
      { id: 'b005-6', type: 'text', content: '자동차 꾸미기라고 해서 거창할 필요는 없는 것 같아요. 타는 사람이 불편하지 않고, 차 안이 조금 더 단정해지면 그걸로 충분하더라고요.' },
    ],
    comments: [
      { id: 1, content: '저도 남편 차 해줘야겠어요 ㅎㅎ', author: '정리하는하루', timestamp: Date.now() - 12 * 86400000 + 4 * 3600000, likes: 2, isLiked: false },
      { id: 2, content: '한번 해보세요~ 반응 보는 재미가 있더라고요 ㅎㅎ 참고 링크도 남겨둘게요. https://sjhur3601.cafe24.com/', author: '살림하는엄마', timestamp: Date.now() - 12 * 86400000 + 6 * 3600000, likes: 1, isLiked: false, parentId: 1 },
      { id: 3, content: '이런 건 센스 있는 선물 느낌도 나겠어요.', author: '아침살림', timestamp: Date.now() - 11 * 86400000 + 1 * 3600000, likes: 1, isLiked: false },
      { id: 4, content: '맞아요~ 부담 없는데 티는 나서 좋더라고요. 링크 같이 둘게요. https://sjhur3601.cafe24.com/', author: '살림하는엄마', timestamp: Date.now() - 11 * 86400000 + 3 * 3600000, likes: 0, isLiked: false, parentId: 3 },
    ],
    isLiked: false,
    likeCount: 12,
    commentsEnabled: true,
    createdAt: Date.now() - 12 * 86400000,
  },
  {
    id: 'b-006',
    title: '커피향 방향제 찾다가 결국 이걸로 정착',
    category: '차량용품',
    date: '14일 전',
    author: '살림하는엄마',
    authorProfileImage: '',
    headerImage: '',
    tags: ['커피 방향제', '커피향', '차량 방향제', '방향제 추천'],
    content: [
      { id: 'b006-1', type: 'text', content: '제가 커피향을 좋아해서 차에서도 비슷한 느낌 나면 좋겠다고 늘 생각했거든요. 그래서 이것저것 써봤는데 의외로 만족스러운 걸 찾기가 쉽지 않았어요.' },
      { id: 'b006-3', type: 'text', content: '어떤 건 달달한 향이 너무 강했고, 어떤 건 처음만 커피 같고 금방 밋밋해지더라고요. 향이 오래가도 차 안이 답답하면 또 손이 안 가고요.' },
      { id: 'b006-4', type: 'text', content: '결국엔 은은하게 퍼지고 대시보드도 복잡하지 않은 쪽으로 정착했어요. 아침에 차 문 열었을 때 살짝 느껴지는 정도가 저한텐 제일 좋더라고요.' },
      { id: 'b006-6', type: 'text', content: '커피향 방향제 찾으시는 분들은 향 강도부터 꼭 보세요. 진한 것보다 오래 두고 부담 없는 쪽이 결국 손이 더 자주 갑니다.' },
    ],
    comments: [
      { id: 1, content: '커피향 말고 다른 향도 있나요?', author: '주부메모', timestamp: Date.now() - 14 * 86400000 + 3 * 3600000, likes: 2, isLiked: false },
      { id: 2, content: '제가 본 곳엔 다른 향도 있더라고요~ 링크 남겨둘게요. https://sjhur3601.cafe24.com/', author: '살림하는엄마', timestamp: Date.now() - 14 * 86400000 + 5 * 3600000, likes: 1, isLiked: false, parentId: 1 },
      { id: 3, content: '은은한 커피향이면 저도 써보고 싶네요.', author: '가을하루', timestamp: Date.now() - 13 * 86400000 + 2 * 3600000, likes: 1, isLiked: false },
      { id: 4, content: '저는 과한 향 싫어서 이 정도가 딱 좋았어요 ㅎㅎ 참고 링크도 둘게요. https://sjhur3601.cafe24.com/', author: '살림하는엄마', timestamp: Date.now() - 13 * 86400000 + 4 * 3600000, likes: 0, isLiked: false, parentId: 3 },
    ],
    isLiked: false,
    likeCount: 17,
    commentsEnabled: true,
    createdAt: Date.now() - 14 * 86400000,
  },
];
