import { type Post } from '@/store/usePostStore';

export const postsBlogA: Post[] = [
  {
    id: 'a-001',
    title: 'G80 출고하고 제일 먼저 한 것',
    category: '차량용품',
    date: '2일 전',
    author: '깔끔한드라이버',
    authorProfileImage: '',
    headerImage: '',
    tags: ['새차', '방향제', 'G80', '대시보드'],
    content: [
      { id: 'a001-1', type: 'text', content: '출고하고 대시보드부터 정리했습니다.' },
      { id: 'a001-3', type: 'text', content: '번호판이랑 방향제를 따로 두는 게 싫어서 겸용으로 하나 올려봤는데, 생각보다 깔끔하게 들어갑니다.' },
      { id: 'a001-5', type: 'text', content: '태양열이라 선 연결도 없고. 요즘 날씨에 햇빛만 들면 알아서 돕니다. 향도 은은한 편이라 거슬리지 않고.' },
      { id: 'a001-6', type: 'text', content: '대시보드 깔끔한 거 좋아하는 분들한테는 괜찮을 듯.' },
    ],
    comments: [
      { id: 1, content: '오 이거 어디서 파는 건가요?', author: '차덕후아저씨', timestamp: Date.now() - 86400000, likes: 2, isLiked: false },
      { id: 2, content: '카페24에서 샀습니다~ https://sjhur3601.cafe24.com/', author: '깔끔한드라이버', timestamp: Date.now() - 82800000, likes: 0, isLiked: false, parentId: 1 },
      { id: 3, content: '혹시 가격대가 어떻게 되나요?', author: '보배드림러', timestamp: Date.now() - 43200000, likes: 1, isLiked: false },
      { id: 4, content: '2만원대였던 거 같습니다. 링크도 같이 남깁니다. https://sjhur3601.cafe24.com/', author: '깔끔한드라이버', timestamp: Date.now() - 39600000, likes: 0, isLiked: false, parentId: 3 },
    ],
    isLiked: false,
    likeCount: 7,
    commentsEnabled: true,
    createdAt: Date.now() - 172800000,
  },
  {
    id: 'a-002',
    title: '주차 알림판 뭐 쓰세요? 번호판 겸용으로 바꿨습니다',
    category: '차량용품',
    date: '4일 전',
    author: '깔끔한드라이버',
    authorProfileImage: '',
    headerImage: '',
    tags: ['주차 알림판', '주차번호판', '차량용품', '대시보드'],
    content: [
      { id: 'a002-1', type: 'text', content: '예전엔 자석식 주차 알림판을 그냥 대시보드에 올려뒀습니다. 급하게 번호 가릴 땐 편했는데, 조금만 주행해도 밀리고 시야에 자꾸 걸리더군요.' },
      { id: 'a002-3', type: 'text', content: '특히 여름엔 접착력이 애매해져서 한 번씩 떨어졌습니다. 전화번호만 보이면 되는 물건인데 왜 이렇게 자리를 많이 차지하나 싶었고요.' },
      { id: 'a002-4', type: 'text', content: '그래서 이번엔 번호판이랑 방향 기능이 같이 들어간 타입으로 바꿨습니다. 하나만 올려두니 대시보드가 덜 복잡해 보이고, 주차할 때 번호 확인도 더 편했습니다.' },
      { id: 'a002-6', type: 'text', content: '이거 쓰기 전엔 번호판은 번호판대로, 향은 향대로 따로 둬서 지저분한 느낌이 있었는데 바꾸고 나서는 눈에 띄는 물건이 하나로 줄었습니다. 깔끔한 거 좋아하시면 이런 방식도 괜찮습니다.' },
    ],
    comments: [
      { id: 1, content: '이거 어디서 구하셨어요? 저도 번호판 바꾸려던 참입니다.', author: 'G90타는형', timestamp: Date.now() - 4 * 86400000 + 3 * 3600000, likes: 2, isLiked: false },
      { id: 2, content: '저는 여기서 봤습니다. https://sjhur3601.cafe24.com/ 겸용이라 자리 덜 차지해서 괜찮더군요.', author: '깔끔한드라이버', timestamp: Date.now() - 4 * 86400000 + 5 * 3600000, likes: 1, isLiked: false, parentId: 1 },
      { id: 3, content: '번호 가리개처럼 여닫는 것도 되나요?', author: '주차매너', timestamp: Date.now() - 4 * 86400000 + 14 * 3600000, likes: 1, isLiked: false },
      { id: 4, content: '네, 잠깐 가릴 때도 불편하지 않았습니다. 링크는 위에 남긴 곳이랑 같습니다. https://sjhur3601.cafe24.com/', author: '깔끔한드라이버', timestamp: Date.now() - 4 * 86400000 + 16 * 3600000, likes: 0, isLiked: false, parentId: 3 },
    ],
    isLiked: false,
    likeCount: 15,
    commentsEnabled: true,
    createdAt: Date.now() - 4 * 86400000,
  },
  {
    id: 'a-003',
    title: '다이소 차량용품 써본 것들 솔직 정리',
    category: '차량용품',
    date: '6일 전',
    author: '깔끔한드라이버',
    authorProfileImage: '',
    headerImage: '',
    tags: ['다이소', '차량용품', '다이소 차량용품', '가성비'],
    content: [
      { id: 'a003-1', type: 'text', content: '다이소 가면 차량용품 코너를 그냥 지나치기가 어렵습니다. 값이 부담 없으니 하나씩 집어오게 되는데, 막상 차에 오래 남는 건 몇 개 안 되더군요.' },
      { id: 'a003-3', type: 'text', content: '송풍구 클립은 급할 때 무난했습니다. 다만 플라스틱 힘이 약해서 몇 번 빼고 끼우니 고정감이 조금 아쉬웠고, 컵홀더 정리 패드는 가격 생각하면 쓸 만했습니다.' },
      { id: 'a003-4', type: 'text', content: '휴대폰 거치 보조 패드는 짧게 쓰기 좋았지만 햇빛 강한 날엔 접착력이 빨리 떨어졌습니다. 물티슈 케이스 걸이는 아이디어는 좋았는데 제 차에서는 손이 잘 안 가더군요.' },
      { id: 'a003-6', type: 'text', content: '결국 지금까지 남은 건 정리 패드 하나랑 대시보드 위를 복잡하지 않게 해주는 물건 정도입니다. 싸다고 무조건 여러 개 두기보다, 매일 손 가는 것만 남기는 게 낫습니다.' },
    ],
    comments: [
      { id: 1, content: '저도 다이소 가면 꼭 하나씩 사 오는데 공감됩니다 ㅎㅎ', author: '세차좋아', timestamp: Date.now() - 6 * 86400000 + 4 * 3600000, likes: 3, isLiked: false },
      { id: 2, content: '가볍게 써보기엔 괜찮은 게 많긴 하죠. 다만 오래 쓸 건 결국 따로 남더군요. https://sjhur3601.cafe24.com/', author: '깔끔한드라이버', timestamp: Date.now() - 6 * 86400000 + 6 * 3600000, likes: 0, isLiked: false, parentId: 1 },
      { id: 3, content: '방향제는 다이소 말고 뭐 쓰세요?', author: '운전은취미', timestamp: Date.now() - 6 * 86400000 + 21 * 3600000, likes: 1, isLiked: false },
      { id: 4, content: '저는 선 정리 안 해도 되는 타입으로 바꿨습니다. 향이 과하지 않아서 괜찮았습니다. https://sjhur3601.cafe24.com/', author: '깔끔한드라이버', timestamp: Date.now() - 6 * 86400000 + 23 * 3600000, likes: 1, isLiked: false, parentId: 3 },
    ],
    isLiked: false,
    likeCount: 11,
    commentsEnabled: true,
    createdAt: Date.now() - 6 * 86400000,
  },
  {
    id: 'a-004',
    title: '다이소 방향제 vs 태양열 방향제, 한 달 써본 후기',
    category: '차량용품',
    date: '8일 전',
    author: '깔끔한드라이버',
    authorProfileImage: '',
    headerImage: '',
    tags: ['다이소 방향제', '태양열 방향제', '방향제 비교', '차량 방향제'],
    content: [
      { id: 'a004-1', type: 'text', content: '한 달 정도 번갈아 써보니 차이가 꽤 분명했습니다. 가격은 다이소 쪽이 부담 없어서 시작하기 좋았고, 향도 처음엔 생각보다 깔끔했습니다.' },
      { id: 'a004-3', type: 'text', content: '문제는 지속력이었습니다. 주말 지나고 나면 향이 거의 안 느껴질 때가 있었고, 더운 날엔 처음 향이 너무 빨리 퍼졌다가 금방 빠지는 느낌이 있었습니다.' },
      { id: 'a004-4', type: 'text', content: '반대로 지금 쓰는 건 햇빛만 들어오면 알아서 움직이는 구조라 선이 없고, 대시보드 위가 덜 어수선합니다. 향이 강하게 치고 들어오진 않는데 대신 오래 남는 편이었습니다.' },
      { id: 'a004-6', type: 'text', content: '가격은 다이소가 확실히 가볍고, 지속력이나 정리감은 지금 쓰는 쪽이 나았습니다. 짧게 써볼 거면 전자도 괜찮고, 오래 둘 생각이면 후자가 더 편했습니다.' },
    ],
    comments: [
      { id: 1, content: '태양열 방향제 가격이 얼마예요?', author: '초보운전중', timestamp: Date.now() - 8 * 86400000 + 2 * 3600000, likes: 1, isLiked: false },
      { id: 2, content: '2만원대였습니다. 저는 여기서 봤습니다. https://sjhur3601.cafe24.com/', author: '깔끔한드라이버', timestamp: Date.now() - 8 * 86400000 + 4 * 3600000, likes: 0, isLiked: false, parentId: 1 },
      { id: 3, content: '소리 나거나 거슬리는 건 없나요?', author: '차알못', timestamp: Date.now() - 8 * 86400000 + 12 * 3600000, likes: 2, isLiked: false },
      { id: 4, content: '제 차에서는 크게 거슬리는 건 없었습니다. 참고하실 만한 링크도 남깁니다. https://sjhur3601.cafe24.com/', author: '깔끔한드라이버', timestamp: Date.now() - 8 * 86400000 + 15 * 3600000, likes: 1, isLiked: false, parentId: 3 },
    ],
    isLiked: false,
    likeCount: 18,
    commentsEnabled: true,
    createdAt: Date.now() - 8 * 86400000,
  },
  {
    id: 'a-005',
    title: '깔끔하게 차 꾸미기, 대시보드 정리 꿀팁',
    category: '차량용품',
    date: '11일 전',
    author: '깔끔한드라이버',
    authorProfileImage: '',
    headerImage: '',
    tags: ['차 꾸미기', '대시보드 정리', '차량 인테리어', '미니멀'],
    content: [
      { id: 'a005-1', type: 'text', content: '차 꾸미기라고 해서 뭘 더 붙이는 것부터 생각하시는 분들이 많습니다. 제 기준에선 반대로 덜어내는 게 먼저였습니다.' },
      { id: 'a005-3', type: 'text', content: '첫째, 대시보드 위 물건 숫자를 줄이십시오. 자주 안 보는 장식은 과감히 빼는 게 시야도 편하고 청소도 쉽습니다.' },
      { id: 'a005-4', type: 'text', content: '둘째, 따로 두던 기능을 하나로 묶으면 생각보다 많이 정리됩니다. 번호 확인용이랑 향 관련 물건을 각각 두는 것보다 겸용으로 두니 훨씬 담백해졌습니다.' },
      { id: 'a005-6', type: 'text', content: '셋째, 색은 한두 가지 안에서 끝내는 게 낫습니다. 결국 대시보드가 깔끔해 보이는 차는 물건이 좋은 차가 아니라, 덜 보여도 되는 것들을 잘 숨긴 차였습니다.' },
    ],
    comments: [
      { id: 1, content: '번호판이랑 방향제 겸용인 거 처음 봤어요.', author: '미니멀라이프', timestamp: Date.now() - 11 * 86400000 + 5 * 3600000, likes: 2, isLiked: false },
      { id: 2, content: '저도 따로 두다가 바꾸고 나니 대시보드가 훨씬 편해졌습니다. 참고 링크 남깁니다. https://sjhur3601.cafe24.com/', author: '깔끔한드라이버', timestamp: Date.now() - 11 * 86400000 + 7 * 3600000, likes: 0, isLiked: false, parentId: 1 },
      { id: 3, content: '확실히 물건 수 줄이는 게 핵심이네요.', author: 'G80산책', timestamp: Date.now() - 10 * 86400000 + 1 * 3600000, likes: 1, isLiked: false },
      { id: 4, content: '맞습니다. 보기 좋게 두는 것보다 안 어지럽게 두는 게 먼저더군요. https://sjhur3601.cafe24.com/', author: '깔끔한드라이버', timestamp: Date.now() - 10 * 86400000 + 3 * 3600000, likes: 0, isLiked: false, parentId: 3 },
    ],
    isLiked: false,
    likeCount: 9,
    commentsEnabled: true,
    createdAt: Date.now() - 11 * 86400000,
  },
  {
    id: 'a-006',
    title: '새차 출고 후 제일 먼저 한 세 가지',
    category: '일상',
    date: '14일 전',
    author: '깔끔한드라이버',
    authorProfileImage: '',
    headerImage: '',
    tags: ['새차', '출고', '블랙박스', '차량용품', '방향제'],
    content: [
      { id: 'a006-1', type: 'text', content: '새차 받으면 이것저것 만지고 싶지만 저는 순서를 딱 세 가지만 먼저 잡습니다. 그래야 괜히 여러 군데 뜯지 않고 필요한 것부터 끝낼 수 있더군요.' },
      { id: 'a006-3', type: 'text', content: '첫 번째는 블랙박스입니다. 출고 첫날부터 주차할 일이 있으니 이건 미루지 않는 게 편했습니다.' },
      { id: 'a006-4', type: 'text', content: '두 번째는 주차할 때 바로 쓸 수 있는 번호 세팅입니다. 임시로 종이 적어두는 건 하루 이틀은 되지만 금방 번거로워집니다.' },
      { id: 'a006-6', type: 'text', content: '세 번째는 차 안 공기부터 정리하는 일입니다. 저는 선 연결 없는 타입을 올려두니 첫날 느낌을 해치지 않아서 좋았습니다. 출고 직후엔 뭘 더하는 것보다 기본을 깔끔하게 맞추는 게 제일 낫습니다.' },
    ],
    comments: [
      { id: 1, content: '방향제 어떤 거예요? 선 연결 없는 건가요?', author: '첫차구매', timestamp: Date.now() - 14 * 86400000 + 4 * 3600000, likes: 2, isLiked: false },
      { id: 2, content: '태양열로 도는 타입이라 선 연결은 없었습니다. 저는 여기서 봤습니다. https://sjhur3601.cafe24.com/', author: '깔끔한드라이버', timestamp: Date.now() - 14 * 86400000 + 6 * 3600000, likes: 1, isLiked: false, parentId: 1 },
      { id: 3, content: '출고 루틴 참고됩니다. 블박 먼저 공감합니다.', author: '신차대기중', timestamp: Date.now() - 13 * 86400000 + 2 * 3600000, likes: 1, isLiked: false },
      { id: 4, content: '처음엔 기본 세팅부터 끝내는 게 마음 편하더군요. 관련 링크도 같이 남깁니다. https://sjhur3601.cafe24.com/', author: '깔끔한드라이버', timestamp: Date.now() - 13 * 86400000 + 5 * 3600000, likes: 0, isLiked: false, parentId: 3 },
    ],
    isLiked: false,
    likeCount: 13,
    commentsEnabled: true,
    createdAt: Date.now() - 14 * 86400000,
  },
];
