import { type Post } from '@/store/usePostStore';

export const postsBlogB: Post[] = [
  {
    id: 'b-001',
    title: '남편 차 탈 때마다 잔소리했는데 이제 안 해요',
    category: '일상',
    date: '3일 전',
    author: '살림하는엄마',
    authorProfileImage: '',
    headerImage: '',
    tags: ['남편 차', '차량 방향제', '차량용품', '일상'],
    content: [
      { id: 'b001-1', type: 'text', content: '남편 차 탈 때마다 \'냄새 좀 나는데\' 싶으면서도 괜히 말 안 하게 되잖아요. 괜히 잔소리처럼 들릴까봐 저도 몇 번은 그냥 참았거든요. 그래서 이번엔 말 대신 제가 조용히 하나 올려놔보자 싶었는데요.' },
      { id: 'b001-2', type: 'image', src: '/posts/b-001-01.jpg', caption: '남편 차에 먼저 올려봤던 방향제' },
      { id: 'b001-3', type: 'text', content: '처음엔 마트에서 송풍구에 끼우는 작은 방향제를 하나 사왔어요. 가격도 부담 없고, 남편 차에 티 안 나게 달아두기 좋겠다 싶었거든요.' },
      { id: 'b001-4', type: 'text', content: '그날 저녁에 남편이 차 타더니 \'어? 오늘은 냄새 괜찮네\' 하면서 웃더라고요. 저도 속으로는 잘됐다 싶었어요. 근데 그게 오래가진 않았어요.' },
      { id: 'b001-5', type: 'text', content: '사흘쯤 지나니까 향이 거의 안 느껴지더라고요. 처음엔 괜찮은가 싶다가도 차 문 열 때마다 다시 답답한 냄새가 올라오니까, 또 갈아줘야 하나 싶어 귀찮았어요. 남편 차 하나 때문에 제가 계속 챙기는 것도 한계가 있잖아요. 그래서 다른 방법을 다시 보게 됐거든요.' },
      { id: 'b001-6', type: 'image', src: '/posts/b-001-02.jpg', caption: '며칠 쓰고 향이 약해진 남편 차 대시보드' },
      { id: 'b001-7', type: 'text', content: '그러다 햇빛 받으면 알아서 돌아가는 타입을 우연히 봤어요. 선도 안 꽂아도 되고, 번호 적는 부분까지 같이 있어서 대시보드가 덜 어수선해 보이더라고요. 이건 제가 계속 손대지 않아도 되겠다 싶었거든요. 그래서 남편 차에 바꿔서 올려봤더니요.' },
      { id: 'b001-8', type: 'image', src: '/posts/b-001-03.jpg', caption: '지금 남편 차에 두고 있는 햇빛 타입' },
      { id: 'b001-9', type: 'text', content: '바꾼 뒤로는 차 탈 때마다 향이 훨씬 은은하게 남아 있어요. 대시보드도 깔끔해져서 남편이 먼저 닦아두는 걸 보면 마음에 든 거 맞는 거죠 ㅎㅎ' },
      { id: 'b001-10', type: 'text', content: '남편 차 냄새 때문에 저처럼 매번 한마디 하게 되시는 분들 있잖아요. 저처럼 자주 갈아끼우는 건 귀찮고 티 안 나게 정리하고 싶으면, 이런 타입도 같이 보셔도 괜찮겠더라고요.' },
    ],
    comments: [
      { id: 1, content: '저도 남편 차 타면 냄새 얘기할까 말까 늘 고민하게 돼요 ㅠㅠ', author: '꽃길걷자', timestamp: Date.now() - 3 * 86400000 + 4 * 3600000, likes: 4, isLiked: false },
      { id: 2, content: '맞아요~ 괜히 한마디 했다가 잔소리처럼 들릴까봐 조심하게 되더라고요 ㅎㅎ', author: '살림하는엄마', timestamp: Date.now() - 3 * 86400000 + 6 * 3600000, likes: 1, isLiked: false, parentId: 1 },
      { id: 3, content: '지금 쓰시는 건 어디서 보셨어요? 선 없는 타입 찾고 있었거든요', author: '다정한주부', timestamp: Date.now() - 3 * 86400000 + 26 * 3600000, likes: 2, isLiked: false },
      { id: 4, content: '저는 여기서 봤어요~ https://sjhur3601.cafe24.com/ 대시보드가 덜 복잡해 보여서 괜찮더라고요', author: '살림하는엄마', timestamp: Date.now() - 3 * 86400000 + 29 * 3600000, likes: 1, isLiked: false, parentId: 3 },
      { id: 5, content: '이런 건 남편이 먼저 알아봐주면 괜히 뿌듯하더라고요 ㅎㅎ', author: '햇살드는집', timestamp: Date.now() - 3 * 86400000 + 49 * 3600000, likes: 3, isLiked: false },
    ],
    isLiked: false,
    likeCount: 12,
    commentsEnabled: true,
    createdAt: Date.now() - 3 * 86400000,
  },
  {
    id: 'b-002',
    title: '남편 생일 선물 뭐 사지? 실용적인 거 골라봤어요',
    category: '일상',
    date: '5일 전',
    author: '살림하는엄마',
    authorProfileImage: '',
    headerImage: '',
    tags: ['남편 생일 선물', '실용적 선물', '남편 선물', '차량용품'],
    content: [
      { id: 'b002-1', type: 'text', content: '남편 생일 선물 뭐 사지 싶을 때가 제일 머리 아프잖아요. 셔츠나 지갑은 이미 있고, 괜히 멋으로 샀다가 안 쓰면 주는 사람만 더 허무하더라고요. 이번엔 진짜 자주 쓰는 걸 골라보자 싶었는데요.' },
      { id: 'b002-2', type: 'image', src: '/posts/b-002-01.jpg', caption: '남편 생일 선물 후보를 모아본 날' },
      { id: 'b002-3', type: 'text', content: '거실 테이블에 텀블러, 양말 세트, 운동화까지 쭉 올려놓고 한참 봤어요. 남편이 평소 뭘 제일 자주 손에 쥐는지 생각해보니까, 의외로 차 안에서 보내는 시간이 길더라고요.' },
      { id: 'b002-4', type: 'text', content: '그래서 매일 눈에 들어오는 쪽으로 마음이 기울었어요. 대시보드가 복잡하지 않게 정리되면서 향도 은은하게 나는 타입이면, 남편도 바로 써보겠겠다 싶었거든요. 근데 제가 이렇게 고른 데는 이유가 있었어요.' },
      { id: 'b002-5', type: 'text', content: '예전엔 보기 좋은 걸로 골랐다가 몇 번 안 쓰고 서랍으로 들어간 적이 있었거든요. 비싼 선물인데 먼지만 쌓이는 거 보면 주는 사람 마음이 더 아깝잖아요. 이번 생일에도 또 그런 걸 주면 어쩌나 싶어서, 예쁜 것보다 쓰는 장면이 바로 떠오르는지를 먼저 봤어요. 그러다 마지막에 딱 남는 게 있더라고요.' },
      { id: 'b002-6', type: 'image', src: '/posts/b-002-02.jpg', caption: '포장해두고도 끝까지 고민했던 생일 선물' },
      { id: 'b002-7', type: 'text', content: '햇빛 받으면 알아서 돌아가는 타입이었는데, 선 연결이 없어서 차 안이 답답해 보이지 않더라고요. 번호 적는 부분까지 같이 있어서 대시보드가 정리되는 느낌도 있었고요. 포장해두니 남편 생일 선물로도 생각보다 단정해 보였거든요. 그래서 생일 아침에 건네봤더니요.' },
      { id: 'b002-8', type: 'image', src: '/posts/b-002-03.jpg', caption: '남편 생일에 준비한 실용적인 선물' },
      { id: 'b002-9', type: 'text', content: '남편이 받자마자 차에 올려봐야겠다면서 웃더라고요. 며칠 지나도 계속 쓰는 거 보니까, 이번엔 서랍행은 아니구나 싶어서 저도 마음이 놓였어요 ㅎㅎ' },
      { id: 'b002-10', type: 'text', content: '남편 생일 선물은 비싼 것보다 자주 쓰는 게 더 오래 기억에 남는 것 같아요. 저처럼 안 쓰는 선물 괜히 아까웠던 분들이라면, 멋보다 실용 쪽을 먼저 보셔도 괜찮겠더라고요.' },
    ],
    comments: [
      { id: 1, content: '저도 남편 생일 선물만 되면 진짜 뭘 사야 하나 막막해져요 ㅠㅠ', author: '봄날햇살', timestamp: Date.now() - 5 * 86400000 + 4 * 3600000, likes: 3, isLiked: false },
      { id: 2, content: '맞아요~ 괜히 멋으로 골랐다가 안 쓰면 더 속상하더라고요 ㅎㅎ', author: '살림하는엄마', timestamp: Date.now() - 5 * 86400000 + 6 * 3600000, likes: 1, isLiked: false, parentId: 1 },
      { id: 3, content: '포장했을 때도 선물 느낌은 괜찮았나요? 너무 생활용품 같을까봐요', author: '고운살림', timestamp: Date.now() - 5 * 86400000 + 26 * 3600000, likes: 2, isLiked: false },
      { id: 4, content: '저는 여기서 보고 골랐어요~ https://sjhur3601.cafe24.com/ 포장해두니 생각보다 단정해서 선물용으로도 괜찮더라고요', author: '살림하는엄마', timestamp: Date.now() - 5 * 86400000 + 29 * 3600000, likes: 1, isLiked: false, parentId: 3 },
      { id: 5, content: '남편들은 결국 매일 쓰는 게 제일 기억에 남는 것 같아요 ㅋㅋ', author: '소박한오늘', timestamp: Date.now() - 5 * 86400000 + 49 * 3600000, likes: 2, isLiked: false },
    ],
    isLiked: false,
    likeCount: 14,
    commentsEnabled: true,
    createdAt: Date.now() - 5 * 86400000,
  },
  {
    id: 'b-003',
    title: '실용적인 선물 고르는 법, 안 쓰면 의미 없잖아요',
    category: '일상',
    date: '7일 전',
    author: '살림하는엄마',
    authorProfileImage: '',
    headerImage: '',
    tags: ['실용적인 선물', '선물 추천', '가성비 선물', '차량용품'],
    content: [
      { id: 'b003-1', type: 'text', content: '실용적인 선물 찾는다고 해도 막상 고르려면 쉽지 않잖아요. 정성껏 챙겨줬는데 몇 번만 쓰고 넣어두는 걸 보면, 주는 사람 마음이 더 허전하더라고요. 저도 그런 일을 몇 번 겪고 나니까 기준이 조금 달라졌는데요.' },
      { id: 'b003-2', type: 'image', src: '/posts/b-003-01.jpg', caption: '서랍에 남아 있던 안 쓰는 선물들' },
      { id: 'b003-3', type: 'text', content: '예전에는 포장 예쁘고 보기 좋은 쪽에 더 끌렸어요. 향수나 소품 같은 것도 챙겨봤는데, 막상 생활이 바쁘면 자주 손이 안 가더라고요.' },
      { id: 'b003-4', type: 'text', content: '그래서 요즘은 집에서든 차에서든 매일 한 번은 보게 되는지를 먼저 봐요. 꺼내 쓰는 과정이 번거롭지 않고, 받아서 바로 써볼 수 있으면 실패 확률이 훨씬 적더라고요. 근데 이 기준이 생긴 데는 이유가 있었어요.' },
      { id: 'b003-5', type: 'text', content: '한 번은 정말 공들여 고른 선물이 있었는데, 다음에 집 갔더니 그대로 서랍 한쪽에 있더라고요. 괜히 \'잘 쓰고 있지?\' 묻기도 민망하고, 받는 사람도 미안해하는 게 보여서 서로 불편했어요. 실용적인 선물이라는 게 결국 비싼 게 아니라 계속 쓰게 되는 거구나 싶었죠. 그 뒤로는 아예 보는 기준을 바꿨거든요.' },
      { id: 'b003-6', type: 'image', src: '/posts/b-003-02.jpg', caption: '몇 번 쓰고 그대로 둔 선물' },
      { id: 'b003-7', type: 'text', content: '특히 차에 있는 시간이 있는 사람은 차 안에서 바로 쓰는 물건이 만족도가 높더라고요. 햇빛 받으면 돌아가고 선 연결도 필요 없는 타입은 설치도 어렵지 않아서 부담이 덜했고요. 대시보드까지 덜 복잡해 보이니까, 받는 사람이 바로 손대보게 되는 거죠. 그래서 요즘은 이런 쪽을 먼저 보게 돼요.' },
      { id: 'b003-8', type: 'image', src: '/posts/b-003-03.jpg', caption: '매일 쓰게 되는 차 안 실용템' },
      { id: 'b003-9', type: 'text', content: '막상 건네고 나서 바로 차에 올려두는 걸 보면 주는 사람도 마음이 놓여요. 몇 주 지나도 계속 쓰는 게 보이면, 그제야 선물이 제대로 갔구나 싶더라고요 ㅎㅎ' },
      { id: 'b003-10', type: 'text', content: '실용적인 선물은 화려한 것보다 생활 안에 자연스럽게 남는 게 중요하더라고요. 저처럼 안 쓰는 선물 보고 괜히 아쉬웠던 분들이라면, 매일 쓰는 장면이 바로 떠오르는지부터 보셔도 괜찮아요.' },
    ],
    comments: [
      { id: 1, content: '차량용품 선물은 생각 못 했는데 진짜 좋은 아이디어네요.', author: '행복한정리', timestamp: Date.now() - 7 * 86400000 + 4 * 3600000, likes: 3, isLiked: false },
      { id: 2, content: '맞아요~ 매일 쓰는 쪽이 결국 만족도가 제일 높더라고요 ㅎㅎ', author: '살림하는엄마', timestamp: Date.now() - 7 * 86400000 + 6 * 3600000, likes: 1, isLiked: false, parentId: 1 },
      { id: 3, content: '받자마자 바로 써볼 수 있는 게 확실히 더 괜찮은 것 같죠?', author: '우리집일상', timestamp: Date.now() - 7 * 86400000 + 26 * 3600000, likes: 2, isLiked: false },
      { id: 4, content: '저는 여기 참고했어요~ https://sjhur3601.cafe24.com/ 바로 올려둘 수 있는 쪽이라 부담이 덜하더라고요', author: '살림하는엄마', timestamp: Date.now() - 7 * 86400000 + 29 * 3600000, likes: 1, isLiked: false, parentId: 3 },
      { id: 5, content: '안 쓰는 선물보다 이런 게 훨씬 오래 기억에 남는 것 같아요 ㅎㅎ', author: '따뜻한살림', timestamp: Date.now() - 7 * 86400000 + 49 * 3600000, likes: 2, isLiked: false },
    ],
    isLiked: false,
    likeCount: 10,
    commentsEnabled: true,
    createdAt: Date.now() - 7 * 86400000,
  },
  {
    id: 'b-004',
    title: '다이소 방향제 1주일 써보고 결국 바꿨어요',
    category: '차량용품',
    date: '9일 전',
    author: '살림하는엄마',
    authorProfileImage: '',
    headerImage: '',
    tags: ['다이소 방향제 추천', '방향제 추천', '차량 방향제', '남편 차'],
    content: [
      // Act 1: Hook
      { id: 'b004-1', type: 'text', content: '남편 차 타면서 \'냄새 나는데\' 싶으면서도 차마 말을 못 한 적 있잖아요. 잔소리처럼 들릴까봐요. 그래서 말 없이 다이소 방향제를 하나 사왔는데요.' },
      { id: 'b004-2', type: 'image', src: '/posts/b-004-01.jpg', caption: '다이소에서 사 온 차량용 방향제' },
      // Act 2: 시도
      { id: 'b004-3', type: 'text', content: '천 원짜리 고체 타입이었어요. 다이소 향 코너 지나가다 하나 집어온 건데, 남편 차 송풍구에 끼우는 거였거든요.' },
      { id: 'b004-4', type: 'text', content: '달아주니까 남편이 "오 향 괜찮은데?" 하면서 좋아했어요. 차 탈 때마다 은은하게 나니까 저도 기분이 좋았거든요. 근데 그게 며칠이었어요.' },
      // Act 3: 실패
      { id: 'b004-5', type: 'text', content: '일주일 지나니까 향이 거의 사라졌어요. 코를 대야 겨우 나는 수준이라, 남편도 "이거 끝난 것 같은데?" 하더라고요. 천 원이라 또 사면 되긴 한데, 매번 갈아끼우는 것도 결국 귀찮잖아요. 그래서 다른 거 없나 찾아봤거든요.' },
      { id: 'b004-6', type: 'image', src: '/posts/b-004-02.jpg', caption: '남편 차 대시보드에 올려둔 모습' },
      // Act 4: 발견
      { id: 'b004-7', type: 'text', content: '그러다 우연히 본 건데, 햇빛 받으면 알아서 돌아가는 타입이 있더라고요. 선도 없고 충전도 필요 없다길래, 이게 진짜 되나 싶었거든요. 그래서 남편한테 보여줬더니요.' },
      { id: 'b004-8', type: 'image', src: '/posts/b-004-03.jpg', caption: '지금 남편 차에 올려둔 방향제' },
      // Act 5: 만족 + 정리
      { id: 'b004-9', type: 'text', content: '바꾼 지 2주 정도 됐는데, 향이 은은하게 계속 유지되고 있어요. 주차번호판 겸용이라 대시보드도 깔끔해졌고요. 남편이 직접 닦고 관리하는 거 보면 마음에 든 거 맞는 거죠 ㅎㅎ' },
      { id: 'b004-10', type: 'text', content: '다이소 방향제가 나쁜 건 아니에요. 가볍게 테스트해보기엔 좋거든요. 근데 저처럼 매번 갈아끼우기 귀찮으면, 다른 쪽도 같이 보시는 게 나을 거예요.' },
    ],
    comments: [
      { id: 1, content: '다이소 방향제 저도 써봤는데 진짜 일주일이면 끝이에요 ㅠㅠ', author: '꽃피는날', timestamp: Date.now() - 9 * 86400000 + 4 * 3600000, likes: 4, isLiked: false },
      { id: 2, content: '맞아요~ 처음엔 괜찮은데 금방 날아가더라고요 ㅎㅎ', author: '살림하는엄마', timestamp: Date.now() - 9 * 86400000 + 6 * 3600000, likes: 1, isLiked: false, parentId: 1 },
      { id: 3, content: '혹시 지금 쓰시는 거 어디서 구매하셨어요? 선 없는 거 찾고 있었거든요', author: '차안이좋아', timestamp: Date.now() - 8 * 86400000 + 2 * 3600000, likes: 2, isLiked: false },
      { id: 4, content: '여기서 봤어요~ https://sjhur3601.cafe24.com/ 번호판 겸용이라 깔끔해요', author: '살림하는엄마', timestamp: Date.now() - 8 * 86400000 + 5 * 3600000, likes: 1, isLiked: false, parentId: 3 },
      { id: 5, content: '남편한테 보여줬더니 본인이 직접 사겠대요 ㅋㅋ', author: '두아이맘', timestamp: Date.now() - 7 * 86400000 + 1 * 3600000, likes: 3, isLiked: false },
    ],
    isLiked: false,
    likeCount: 16,
    commentsEnabled: true,
    createdAt: Date.now() - 9 * 86400000,
  },
  {
    id: 'b-005',
    title: '남편 차 몰래 꾸며줬더니 반응이 ㅎㅎ',
    category: '일상',
    date: '12일 전',
    author: '살림하는엄마',
    authorProfileImage: '',
    headerImage: '',
    tags: ['자동차 꾸미기', '남편 차', '차량 인테리어', '깜짝 선물'],
    content: [
      { id: 'b005-1', type: 'text', content: '자동차 꾸미기라고 하면 거창하게 생각하시는 분들 많잖아요. 근데 저는 남편 차는 티 안 나게 조금만 손보는 쪽이 더 좋더라고요. 이번에도 몰래 대시보드 쪽만 정리해보자 싶었는데요.' },
      { id: 'b005-2', type: 'image', src: '/posts/b-005-01.jpg', caption: '정리하기 전 남편 차 대시보드' },
      { id: 'b005-3', type: 'text', content: '처음엔 작은 장식 하나 놓고, 번호 적는 것도 따로 두고, 향 나는 것도 하나 올려봤어요. 제가 보기엔 귀엽고 알차 보였는데, 막상 남편 차에 두니까 생각보다 이것저것 많아 보이더라고요.' },
      { id: 'b005-4', type: 'text', content: '그래도 하루쯤은 괜찮은가 싶었어요. 근데 차 문 열 때마다 시선이 분산되고, 급하게 브레이크 밟으면 작은 것들이 조금씩 움직이니까 제가 봐도 마음이 불편하더라고요. 이대로 두면 남편이 더 싫어하겠다 싶었죠.' },
      { id: 'b005-5', type: 'text', content: '남편이 원래 복잡한 걸 별로 안 좋아하거든요. 예전에 하나 더 올려뒀다가 \'차가 좀 정신없네\' 소리 들은 적도 있어서, 괜히 또 그 말 나오면 제가 민망하잖아요. 자동차 꾸미기도 결국 타는 사람이 편해야 의미가 있는 건데, 저는 제 취향만 앞세운 셈이더라고요. 그래서 하나로 정리되는 걸 다시 찾게 됐어요.' },
      { id: 'b005-6', type: 'image', src: '/posts/b-005-02.jpg', caption: '이것저것 올려뒀다가 복잡해진 대시보드' },
      { id: 'b005-7', type: 'text', content: '그러다 햇빛 받으면 돌아가면서 번호 적는 부분까지 같이 있는 타입을 봤어요. 선이 없으니까 걸리적거리지 않고, 따로따로 두던 걸 하나로 줄일 수 있겠더라고요. 이런 건 남편 차에 올려놔도 티는 나는데 부담은 덜하겠다 싶었거든요. 그래서 조용히 바꿔놨더니요.' },
      { id: 'b005-8', type: 'image', src: '/posts/b-005-03.jpg', caption: '하나로 정리해둔 지금 남편 차' },
      { id: 'b005-9', type: 'text', content: '퇴근하고 탄 남편이 \'어? 차가 왜 이렇게 깔끔해졌지\' 하더라고요. 제가 했다고 하니까 웃으면서 이런 건 괜찮다길래, 저도 괜히 뿌듯했어요 ㅎㅎ' },
      { id: 'b005-10', type: 'text', content: '자동차 꾸미기는 결국 많이 올려두는 것보다 덜어내는 쪽이 더 예쁜 것 같아요. 저처럼 남편 차를 소소하게 손보고 싶으시면, 하나로 정리되는 타입부터 보셔도 괜찮겠더라고요.' },
    ],
    comments: [
      { id: 1, content: '저도 남편 차 한번 몰래 손봐줘야겠어요 ㅎㅎ', author: '정리하는하루', timestamp: Date.now() - 12 * 86400000 + 4 * 3600000, likes: 3, isLiked: false },
      { id: 2, content: '한번 해보세요~ 너무 티 나지 않게 바꿔두면 반응 보는 재미가 있더라고요 ㅎㅎ', author: '살림하는엄마', timestamp: Date.now() - 12 * 86400000 + 6 * 3600000, likes: 1, isLiked: false, parentId: 1 },
      { id: 3, content: '번호판이랑 같이 되는 거면 더 깔끔하겠네요. 어디서 보셨어요?', author: '아침살림', timestamp: Date.now() - 12 * 86400000 + 26 * 3600000, likes: 2, isLiked: false },
      { id: 4, content: '저는 여기서 봤어요~ https://sjhur3601.cafe24.com/ 하나로 정리되니까 대시보드가 훨씬 편안해 보이더라고요', author: '살림하는엄마', timestamp: Date.now() - 12 * 86400000 + 29 * 3600000, likes: 1, isLiked: false, parentId: 3 },
      { id: 5, content: '남편들은 티 안 나게 바뀐 걸 더 좋아하더라고요 ㅋㅋ', author: '오전의살림', timestamp: Date.now() - 12 * 86400000 + 49 * 3600000, likes: 2, isLiked: false },
    ],
    isLiked: false,
    likeCount: 12,
    commentsEnabled: true,
    createdAt: Date.now() - 12 * 86400000,
  },
  {
    id: 'b-006',
    title: '커피향 방향제 찾다가 결국 이걸로 정착',
    category: '차량용품',
    date: '14일 전',
    author: '살림하는엄마',
    authorProfileImage: '',
    headerImage: '',
    tags: ['커피 방향제', '커피향', '차량 방향제', '방향제 추천'],
    content: [
      { id: 'b006-1', type: 'text', content: '커피향 방향제 찾는 분들 마음 저도 너무 잘 알거든요. 저도 커피 냄새 좋아해서 차 문 열 때도 그런 느낌이 살짝 나면 좋겠다 싶었어요. 근데 막상 써보면 생각보다 딱 맞는 걸 찾기가 쉽지 않더라고요.' },
      { id: 'b006-2', type: 'image', src: '/posts/b-006-01.jpg', caption: '커피향 계열로 이것저것 비교해본 날' },
      { id: 'b006-3', type: 'text', content: '처음엔 달달한 쪽도 써보고, 묵직한 원두 느낌 난다는 것도 써봤어요. 부엌 테이블에 몇 개 올려두고 맡아보면 괜찮은데, 차 안에 두면 느낌이 또 달라지더라고요.' },
      { id: 'b006-4', type: 'text', content: '아침에 차 문 열었을 때 은은하게 올라오는 게 제일 좋겠다 싶었거든요. 그래서 향이 강하지 않고, 대시보드도 복잡해 보이지 않는 쪽으로 기준을 세웠어요. 근데 거기서부터가 더 어렵더라고요.' },
      { id: 'b006-5', type: 'text', content: '어떤 건 커피향보다는 달달한 시럽 냄새가 더 강해서 오래 타고 있으면 머리가 답답했어요. 또 어떤 건 처음만 커피 같고 며칠 지나면 그냥 밋밋해져서, 굳이 차에 둘 이유를 모르겠더라고요. 커피향 방향제라고 다 같은 게 아니구나 싶으니까 더 고르기 까다로워졌죠. 그래서 아예 보는 포인트를 바꿔봤어요.' },
      { id: 'b006-6', type: 'image', src: '/posts/b-006-02.jpg', caption: '향은 괜찮아도 답답했던 이전 타입들' },
      { id: 'b006-7', type: 'text', content: '그러다 햇빛 받으면 돌아가는 타입을 봤는데, 선 연결이 없어서 차 안이 훨씬 가벼워 보이더라고요. 향도 확 세게 밀어붙이는 느낌이 아니라, 문 열었을 때만 살짝 느껴지는 쪽이라 이건 괜찮겠다 싶었어요. 대시보드에 올려도 답답해 보이지 않는 게 제일 마음에 들었거든요. 그래서 결국 이걸로 바꿔봤죠.' },
      { id: 'b006-8', type: 'image', src: '/posts/b-006-03.jpg', caption: '지금 차 안에서 쓰는 커피향 타입' },
      { id: 'b006-9', type: 'text', content: '지금은 아침에 차 문 열면 은은하게 커피향이 먼저 느껴져서 기분이 좋더라고요. 너무 진하지 않으니까 오래 타고 있어도 부담이 없고, 대시보드도 깔끔해서 저는 이 정도가 딱 좋았어요 ㅎㅎ' },
      { id: 'b006-10', type: 'text', content: '커피향 방향제 찾으시면 진한 향보다 오래 두고도 답답하지 않은지를 먼저 보셔야 하더라고요. 저처럼 커피 느낌은 좋지만 차 안이 무거워지는 건 싫으신 분들께는 이런 쪽이 더 잘 맞을 것 같아요.' },
    ],
    comments: [
      { id: 1, content: '커피향 좋아하는데 차 안에서는 너무 진하면 머리 아프더라고요 ㅠ', author: '주부메모', timestamp: Date.now() - 14 * 86400000 + 4 * 3600000, likes: 3, isLiked: false },
      { id: 2, content: '맞아요~ 저도 달달한 쪽은 오래 타면 좀 답답해서 못 쓰겠더라고요', author: '살림하는엄마', timestamp: Date.now() - 14 * 86400000 + 6 * 3600000, likes: 1, isLiked: false, parentId: 1 },
      { id: 3, content: '커피향 말고 다른 향도 같이 있나요? 은은한 쪽이면 보고 싶어요', author: '가을하루', timestamp: Date.now() - 14 * 86400000 + 26 * 3600000, likes: 2, isLiked: false },
      { id: 4, content: '저는 여기서 봤어요~ https://sjhur3601.cafe24.com/ 다른 향도 있던데 저는 과하지 않은 커피 쪽이 제일 낫더라고요', author: '살림하는엄마', timestamp: Date.now() - 14 * 86400000 + 29 * 3600000, likes: 1, isLiked: false, parentId: 3 },
      { id: 5, content: '은은한 커피향이면 아침 출근길에 딱일 것 같네요 ㅎㅎ', author: '소소한메모', timestamp: Date.now() - 14 * 86400000 + 49 * 3600000, likes: 2, isLiked: false },
    ],
    isLiked: false,
    likeCount: 17,
    commentsEnabled: true,
    createdAt: Date.now() - 14 * 86400000,
  },
];
